#!/usr/bin/python3
# -*- coding: utf-8 -*-

from datetime import datetime
from datetime import timezone
from json import dumps as dump_to_json
from urllib.parse import parse_qs
from wsgiref.simple_server import make_server

from includes.mqtt import publish  # pylint: disable=no-name-in-module


def convert_value(value):
    if len(value) == 1:
        return value[0]
    return value


def update_fields(environ):
    query = environ.get("QUERY_STRING") or ""
    path = environ.get("PATH_INFO") or ""
    if query:
        raw = parse_qs(query)
    elif "AMBWeather" in path or "dateutc=" in path:
        raw = parse_qs(path)
    else:
        return None

    fields = {}
    for key, value in raw.items():
        field = key[key.rfind("/") + 1 :] if "/" in key else key
        fields[field] = convert_value(value)

    station_types = raw.get("stationtype", [])
    station_hit = any("AMBWeather" in item for item in station_types)
    if not (station_hit or "dateutc" in fields or "AMBWeather" in path):
        return None
    if "dateutc" not in fields:
        return None
    return fields


def listener(environ, start_response):
    data_dict = update_fields(environ)
    if data_dict is not None:
        utc = datetime.strptime(data_dict.pop("dateutc"), "%Y-%m-%d %H:%M:%S")
        utc = utc.replace(tzinfo=timezone.utc)
        local_time = utc.astimezone()

        time_string_payload = local_time.strftime("%Y-%m-%d %H:%M:%S")
        json_payload = dump_to_json(data_dict)

        publish("weather", time_string_payload)
        publish("weather/attributes", json_payload)

        start_response("200 OK", [("Content-Type", "text/plain")])
        response_body = ""
        return [response_body.encode()]

    start_response("400 Bad Request", [("Content-Type", "text/plain")])
    response_body = ""
    return [response_body.encode()]


def main():
    httpd = make_server("", 80, listener)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
