#!/usr/bin/python3
# -*- coding: utf-8 -*-

# System Imports
from logging import ERROR
from logging import INFO
from multiprocessing import Process
from os import _exit as exit_now
from os import chdir
from os import close as os_close
from os import fdopen
from os import getenv
from os import pipe as os_pipe
from os import remove
from pathlib import Path
from pathlib import PurePath
from pickle import dump as pickle_dump
from pickle import load as pickle_load
from signal import SIGABRT
from signal import SIGINT
from signal import SIGTERM
from signal import signal
from subprocess import PIPE
from subprocess import Popen
from subprocess import run
from threading import Thread
from time import sleep

# Local Imports
from includes.fabric import fetch  # pylint: disable=no-name-in-module
from includes.fabric import release_version  # pylint: disable=no-name-in-module
from includes.python_logger import create_logger  # pylint: disable=no-name-in-module

RAM_DRIVE = "/mnt/ramdisk/"
NFS_DRIVE = "/mnt/minecraft/"
DATA_STORE = "/mnt/minecraft/store.pckl"
SAVE_INTERVAL = 300
# PID 1 is killed when this budget runs out. docker stop -t and
# terminationGracePeriodSeconds have to be at least STOP_GRACE_SECONDS.
STOP_WAIT_SECONDS = 20
COPY_TIMEOUT_SECONDS = 150
STOP_GRACE_SECONDS = STOP_WAIT_SECONDS + COPY_TIMEOUT_SECONDS + 10

FOLDER_LIST = []
FOLDER_LIST.append("world")
FOLDER_LIST.append("config")

FILE_LIST = []
FILE_LIST.append("banned-ips.json")
FILE_LIST.append("banned-players.json")
FILE_LIST.append("ops.json")
FILE_LIST.append("eula.txt")
FILE_LIST.append("server.properties")
FILE_LIST.append("whitelist.json")

# free reports KiB. "max" and the v1 sentinel both mean the cgroup limit is unset.
CGROUP_V2_MAX = "/sys/fs/cgroup/memory.max"
CGROUP_V1_LIMIT = "/sys/fs/cgroup/memory/memory.limit_in_bytes"
ONE_GB_IN_FREE_UNITS = 1_000_000
UNLIMITED_CGROUP_BYTES = 1 << 60


def read_cgroup_text(path):
    try:
        return Path(path).read_text(encoding="utf-8")
    except OSError:
        return None


def free_total_kb():
    completed = run("/usr/bin/free", stdout=PIPE, check=True)
    return int(completed.stdout.decode("utf-8").split("\n")[1].split()[1])


def memory_limit_kb(read_text, read_free_kb):
    v2_text = read_text(CGROUP_V2_MAX)
    if v2_text is not None and v2_text.strip() and v2_text.strip() != "max":
        return int(v2_text.strip()) // 1024

    v1_text = read_text(CGROUP_V1_LIMIT)
    if v1_text is not None and int(v1_text.strip()) < UNLIMITED_CGROUP_BYTES:
        return int(v1_text.strip()) // 1024

    return read_free_kb()


def heap_gigabytes(limit_kb):
    if limit_kb < ONE_GB_IN_FREE_UNITS:
        raise RuntimeError(
            f"Refusing to start: memory limit {limit_kb} kB is under 1 GB"
        )
    return max(1, int((limit_kb / ONE_GB_IN_FREE_UNITS) * 0.25))


class LogPipe(Thread):  # pylint: disable=too-many-instance-attributes
    def __init__(self, base_logger, level):
        # pylint: disable=invalid-name
        Thread.__init__(self)
        self.daemon = True
        self.level = level
        self.fdRead, self.fdWrite = os_pipe()
        self.pipeReader = fdopen(self.fdRead)
        self.base_logger = base_logger
        self._watch_for_value = False
        self._watched_value = None
        self._watched_values = []
        self.watched_value_found = False
        self.start()

    def fileno(self):
        return self.fdWrite

    def run(self):
        for line in iter(self.pipeReader.readline, ""):
            clean_line = line.strip("\n")
            if self._watch_for_value:
                if any(substring in clean_line for substring in self._watched_values):
                    self.watched_value_found = True
            self.base_logger.log(self.level, clean_line)

        self.pipeReader.close()

    def close(self):
        os_close(self.fdWrite)

    def watch_for_value(self, *watch_values):
        if watch_values:
            self._watch_for_value = True
            self._watched_values = list(watch_values)
        else:
            self._watch_for_value = False
            self._watched_value = None
        self.watched_value_found = False


LOGGER = create_logger(PurePath(__file__).stem)
LOGINFO = LogPipe(LOGGER, INFO)
LOGERR = LogPipe(LOGGER, ERROR)

LOGGER.setLevel(INFO)


CHILD_PROCESS = None
SHUTTING_DOWN = False


def tell_server(process, line):
    try:
        process.stdin.write(line)
        process.stdin.flush()
    except BrokenPipeError:
        LOGGER.warning("Server closed its console")


def mirror(source, target, **options):
    from dirsync import sync

    Path(target).mkdir(parents=True, exist_ok=True)
    try:
        sync(
            source,
            target,
            "sync",
            logger=LOGGER,
            verbose=True,
            create=True,
            **options,
        )
    except Exception:  # pylint: disable=broad-except
        LOGGER.exception("Sync failed from %s to %s", source, target)
        raise


def copy_directory_to_storage(sub_path):
    mirror(f"{RAM_DRIVE}{sub_path}", f"{NFS_DRIVE}{sub_path}", purge=True)


def copy_files_to_storage():
    mirror(RAM_DRIVE, NFS_DRIVE, only=FILE_LIST)
    source_root = Path(RAM_DRIVE)
    target_root = Path(NFS_DRIVE)
    for name in FILE_LIST:
        target = target_root / name
        if not (source_root / name).exists() and target.is_file():
            target.unlink()


def sync_copy(ram_to_data_store=True):
    if ram_to_data_store:
        for folder in FOLDER_LIST:
            copy_directory_to_storage(folder)
        copy_files_to_storage()
        return

    mirror(NFS_DRIVE, RAM_DRIVE, purge=True)


def save(process):
    if process.poll() is None:
        tell_server(process, b"save-off\n")
        tell_server(process, b"save-all\n")

        LOGINFO.watch_for_value("Saved the game", "RCON Listener stopped")
        counter = 0
        while not LOGINFO.watched_value_found and counter < 90:
            sleep(1)
            counter = counter + 1

        save_process = Process(target=sync_copy)

        save_process.start()
        save_process.join(timeout=COPY_TIMEOUT_SECONDS)

        if save_process.is_alive():
            save_process.kill()
            LOGGER.error("Sync Timed Out Stopping Minecraft Server")
            copy_ok = False
        elif save_process.exitcode != 0:
            LOGGER.error("Sync failed")
            copy_ok = False
        else:
            copy_ok = True

        if copy_ok:
            tell_server(process, b"save-on\n")
        else:
            tell_server(process, b"stop\n")


def shutdown(process, exit_fn=exit_now):
    if process is None:
        LOGGER.info("Server never started")
        LOGINFO.close()
        LOGERR.close()
        exit_fn(0)
        return  # pylint: disable=unreachable

    LOGGER.info("Starting Final Sync")
    if process.poll() is None:
        tell_server(process, b"stop\n")

        counter = 0
        LOGINFO.watch_for_value("RCON Listener stopped")
        while not LOGINFO.watched_value_found and counter < STOP_WAIT_SECONDS:
            sleep(1)
            counter = counter + 1

    save_process = Process(target=sync_copy)

    save_process.start()
    save_process.join(timeout=COPY_TIMEOUT_SECONDS)

    if save_process.is_alive():
        save_process.kill()
        LOGGER.error("Final Sync Timed out")
        copy_ok = False
    elif save_process.exitcode != 0:
        LOGGER.error("Final Sync failed")
        copy_ok = False
    else:
        LOGGER.info("Finished Final Sync")
        copy_ok = True

    LOGINFO.close()
    LOGERR.close()

    exit_code = process.poll()
    if exit_code is None:
        process.kill()
        exit_code = 9999
    if not copy_ok and exit_code == 0:
        exit_code = 1

    exit_fn(exit_code)


def save_and_exit():
    shutdown(CHILD_PROCESS)


def exit_after_failure(process, exit_fn=exit_now):
    if process is None:
        LOGINFO.close()
        LOGERR.close()
        exit_fn(1)
        return  # pylint: disable=unreachable
    shutdown(process, exit_fn=exit_fn)


def signal_handler(_sig, _frame):
    global SHUTTING_DOWN  # pylint: disable=global-statement
    if SHUTTING_DOWN:
        exit_now(1)
    SHUTTING_DOWN = True
    try:
        save_and_exit()
    except Exception:  # pylint: disable=broad-except
        LOGGER.exception("Shutdown failed")
        exit_now(1)


def log_retry(url, attempt, attempts, error, delay):
    LOGGER.warning(
        "Fetch %s failed (%s/%s): %s; retrying in %ss",
        url,
        attempt,
        attempts,
        error,
        delay,
    )


def install_fabric(minecraft_version):
    from requests import get as http_get
    from xmltodict import parse as xml_parse

    fabric_base_url = "https://maven.fabricmc.net/net/fabricmc/fabric-installer/"
    fabric_metadata_url = f"{fabric_base_url}maven-metadata.xml"

    metadata = fetch(
        fabric_metadata_url,
        get=http_get,
        sleep=sleep,
        log=log_retry,
    )
    fabric_version = release_version(xml_parse(metadata.content))

    fabric_download_url = (
        f"{fabric_base_url}{fabric_version}/fabric-installer-{fabric_version}.jar"
    )
    fabric_download = fetch(
        fabric_download_url,
        get=http_get,
        sleep=sleep,
        log=log_retry,
    )

    fabric_installer = Path(f"{RAM_DRIVE}fabric-installer.jar")
    LOGGER.info(fabric_installer)
    with open(fabric_installer, "wb") as installer:
        installer.write(fabric_download.content)

    if fabric_installer.is_file():
        chdir(RAM_DRIVE)
        fabric_install_script = []
        fabric_install_script.append("/usr/bin/java")
        fabric_install_script.append("-jar")
        fabric_install_script.append(f"{RAM_DRIVE}fabric-installer.jar")
        fabric_install_script.append("server")
        fabric_install_script.append("-mcversion")
        fabric_install_script.append(f"{minecraft_version}")
        fabric_install_script.append("-downloadMinecraft")
        fabric_install_script.append("-dir")
        fabric_install_script.append(f"{RAM_DRIVE}")

        LOGGER.info(fabric_install_script)

        fabric_install = Popen(  # pylint: disable=consider-using-with
            fabric_install_script, stdin=PIPE, stdout=LOGINFO, stderr=LOGERR
        )
        fabric_install.wait()
        remove("fabric-installer.jar")


def start_minecraft(version_change=False):
    chdir(RAM_DRIVE)

    minecraft_ram = heap_gigabytes(memory_limit_kb(read_cgroup_text, free_total_kb))

    LOGGER.info("Using %sG RAM for Minecraft", minecraft_ram)

    # https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
    start_server_script = []
    start_server_script.append("/usr/bin/java")
    start_server_script.append(f"-Xms{minecraft_ram}G")
    start_server_script.append(f"-Xmx{minecraft_ram}G")
    start_server_script.append("-XX:+UseG1GC")
    start_server_script.append("-XX:+ParallelRefProcEnabled")
    start_server_script.append("-XX:MaxGCPauseMillis=200")
    start_server_script.append("-XX:+UnlockExperimentalVMOptions")
    start_server_script.append("-XX:+DisableExplicitGC")
    start_server_script.append("-XX:+AlwaysPreTouch")

    if minecraft_ram > 12:
        start_server_script.append("-XX:G1NewSizePercent=40")
        start_server_script.append("-XX:G1MaxNewSizePercent=50")
        start_server_script.append("-XX:G1HeapRegionSize=16M")
        start_server_script.append("-XX:G1ReservePercent=15")
    else:
        start_server_script.append("-XX:G1NewSizePercent=30")
        start_server_script.append("-XX:G1MaxNewSizePercent=40")
        start_server_script.append("-XX:G1HeapRegionSize=8M")
        start_server_script.append("-XX:G1ReservePercent=20")

    start_server_script.append("-XX:G1HeapWastePercent=5")
    start_server_script.append("-XX:G1MixedGCCountTarget=4")

    if minecraft_ram > 12:
        start_server_script.append("-XX:InitiatingHeapOccupancyPercent=20")
    else:
        start_server_script.append("-XX:InitiatingHeapOccupancyPercent=15")

    start_server_script.append("-XX:G1MixedGCLiveThresholdPercent=90")
    start_server_script.append("-XX:G1RSetUpdatingPauseTimePercent=5")
    start_server_script.append("-XX:SurvivorRatio=32")
    start_server_script.append("-XX:+PerfDisableSharedMem")
    start_server_script.append("-XX:MaxTenuringThreshold=1")
    start_server_script.append("-Dusing.aikars.flags=https://mcflags.emc.gs")
    start_server_script.append("-Daikars.new.flags=true")
    start_server_script.append("-jar")

    start_server_script.append(f"{RAM_DRIVE}fabric-server-launch.jar")
    start_server_script.append("--nogui")
    if version_change:
        start_server_script.append("--eraseCache")
        start_server_script.append("--forceUpgrade")

    return Popen(  # pylint: disable=consider-using-with
        start_server_script, stdin=PIPE, stdout=LOGINFO, stderr=LOGERR
    )


def accept_eula():
    if getenv("EULA", "").lower() != "true":
        return
    path = Path(RAM_DRIVE) / "eula.txt"
    path.write_text(
        "#By changing the setting below to TRUE you are indicating your agreement "
        "to our EULA (https://aka.ms/MinecraftEULA).\n"
        "eula=true\n",
        encoding="utf-8",
    )


def remember_version(version):
    with open(DATA_STORE, "wb") as store:
        pickle_dump(version, store)


def wait_until_ready(process):
    counter = 0
    LOGINFO.watched_value_found = False
    LOGINFO.watch_for_value("RCON running")
    while process.poll() is None:
        counter = counter + 1
        if LOGINFO.watched_value_found:
            return True
        if counter > SAVE_INTERVAL:
            return False
        sleep(5)
    return False


def exit_without_copy(process):
    code = process.poll() or 1
    LOGINFO.close()
    LOGERR.close()
    exit_now(code)


def main():
    signal(SIGINT, signal_handler)
    signal(SIGABRT, signal_handler)
    signal(SIGTERM, signal_handler)

    minecraft_version = getenv("MINECRAFT_VERSION", "1.17")
    version_change = True
    try:
        with open(DATA_STORE, "rb") as store:
            previous_minecraft_version = pickle_load(store)
            version_change = minecraft_version != previous_minecraft_version
    except OSError:
        LOGGER.info("Failed to find previous Minecraft Version")

    install_fabric(minecraft_version)

    sync_copy(ram_to_data_store=False)
    accept_eula()

    global CHILD_PROCESS  # pylint: disable=global-statement
    CHILD_PROCESS = start_minecraft(version_change)

    ready = wait_until_ready(CHILD_PROCESS)
    if CHILD_PROCESS.poll() is not None and not ready:
        exit_without_copy(CHILD_PROCESS)
        return

    if ready and version_change:
        remember_version(minecraft_version)

    counter = 0
    LOGINFO.watch_for_value("RCON Listener stopped")
    while CHILD_PROCESS.poll() is None and not LOGINFO.watched_value_found:
        if counter > SAVE_INTERVAL:
            save(CHILD_PROCESS)
            LOGINFO.watch_for_value("RCON Listener stopped")
            counter = 0
        else:
            counter = counter + 1

        sleep(1)

    save_and_exit()


if __name__ == "__main__":
    try:
        main()
    except Exception:  # pylint: disable=broad-except
        LOGGER.exception("Minecraft startup failed")
        exit_after_failure(CHILD_PROCESS)
