#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys
from os import environ
from os import execv
from pathlib import Path
from subprocess import run


def setup_scripts(directory):
    directory = Path(directory)
    if not directory.is_dir():
        return []
    scripts = [
        path
        for path in directory.iterdir()
        if path.is_file() and path.stem != "__init__"
    ]
    scripts.sort(key=lambda path: path.name)
    return scripts


def run_setup(scripts, run_script):
    for script in scripts:
        status = run_script(script)
        if status:
            return status
    return 0


def start(argv, setup_dir, finalize, run_script, exec_fn):
    environ["PYTHONPATH"] = "/scripts:/scripts/includes"
    status = run_setup(setup_scripts(setup_dir), run_script)
    if status:
        return status
    exec_fn(finalize, ["finalize", *argv[1:]])
    return 0


def _run_script(path):
    completed = run([str(path)], check=False)
    return completed.returncode


if __name__ == "__main__":
    code = start(sys.argv, "/scripts/setup", "/scripts/finalize", _run_script, execv)
    if code:
        sys.exit(code)
